export const constApiRoute = {
  lotofacil: 'api/lotofacil',
  lotofacilLast: 'api/lotofacil/last',
  lotofacilNumeros: 'api/lotofacil/numeros',
  lotofacilNumerosSaindo: 'api/lotofacil/numeros-saindo',
  lotofacilNumerosNaoSaindo: 'api/lotofacil/numeros-atrasados',
  lotofacilCiclo: 'api/lotofacil/ciclo/simples',
  lotofacilCicloDuplo: 'api/lotofacil/ciclo/duplo',
  lotofacilCicloDuploNo: 'api/lotofacil/ciclo/no-duplo',
  lotofacilCicloTriplo: 'api/lotofacil/ciclo/triplo',
  lotofacilCicloTriploNo: 'api/lotofacil/ciclo/no-triplo',
  lotofacilCicloLinha1: 'api/lotofacil/ciclo/linha1',  
  lotofacilCicloLinha2: 'api/lotofacil/ciclo/linha2',
  lotofacilCicloLinha3: 'api/lotofacil/ciclo/linha3',
  lotofacilCicloLinha4: 'api/lotofacil/ciclo/linha4',
  lotofacilCicloLinha5: 'api/lotofacil/ciclo/linha5',
  lotofacilCicloImpares: 'api/lotofacil/ciclo/impares',
  lotofacilCicloPares: 'api/lotofacil/ciclo/pares',
  lotofacilCicloColuna1: 'api/lotofacil/ciclo/coluna1',
  lotofacilCicloColuna2: 'api/lotofacil/ciclo/coluna2',
  lotofacilCicloColuna3: 'api/lotofacil/ciclo/coluna3',
  lotofacilCicloColuna4: 'api/lotofacil/ciclo/coluna4',
  lotofacilCicloColuna5: 'api/lotofacil/ciclo/coluna5',

  lotofacilCaixa : 'api/caixa/lotofacil',
  lotofacilCaixaShow: 'api/caixa/lotofacil/show/',
  lotofacilUpdate: 'api/lotofacil/atualiza',
}